# Site settings
title: Streaming Data Solutions
email: foxmike@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Streaming Data Architectures featuring Scalable Routing of Data, Transformation, Validation, Profiling, Comparison, Normalization and Cross Referencing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: whipstitched
github_username:  foxmike

# Build settings
markdown: kramdown